type Portfolio = {
  id: number
  title: string
  image: string
  url: string
  rating: number
  recommended?: boolean
}

export const portfolios: Portfolio[] = [
  { id: 1, title: "Enrique Paulino", image: "/images/enrique-paulino.png", url: "https://enrique-paulino.github.io/", rating: 2.67},
  { id: 2, title: "Ras Mic", image: "/images/rasmic.png", url: "https://www.rasmic.xyz/", rating: 4.0},
  { id: 3, title: "Achyuth S S", image: "/images/achyudev.png", url: "https://achyudev.vercel.app/", rating: 2.83},
  { id: 4, title: "Nike Suputra", image: "/images/fourleaves.png", url: "https://resume.fourleaves.studio/", rating: 2.83},
  { id: 5, title: "Joshua Onyeuche", image: "/images/joshuaonyeuche.png", url: "https://joshuaonyeuche.com/", rating: 1.0},
  { id: 6, title: "Aldo Fernando Vilardy Roa", image: "/images/aldovilardy.png", url: "https://aldovilardy.azurewebsites.net/", rating: 2.5},
  { id: 7, title: "Prasoon Mahawar", image: "/images/prasoon.png", url: "https://prasoon-mahawar.dev/", rating: 4.17},
  { id: 8, title: "Andy Sharma", image: "/images/andysharma.png", url: "https://andysharma.vercel.app/", rating: 2.17},
  { id: 9, title: "Aaditya Srivastava", image: "/images/sumionochi.png", url: "https://sumionochi.github.io/Portfolio-landing-page/", rating: 2.83},
  { id: 10, title: "Manish Gotame", image: "/images/manishgotame.png", url: "https://www.manishgotame.com.np/", rating: 2.0},
  { id: 11, title: "Dushyanth Gali", image: "/images/dushyanth.png", url: "https://dushyanth.in/", rating: 2.33},
  { id: 12, title: "Daniel Moya", image: "/images/moyadaniel.png", url: "https://moyadaniel.com/", rating: 3.33},
  { id: 13, title: "Binil B", image: "/images/thegr8binil.png", url: "https://www.thegr8binil.me/ContactMe", rating: 4.67, recommended: true},
  { id: 14, title: "Arjun Bector", image: "/images/arjunbector.png", url: "https://arjunbector.live/", rating: 4.17, recommended: true},
  { id: 15, title: "Mayank Ughade", image: "/images/mayank-ughade.png", url: "https://mayank-ughade.vercel.app/", rating: 3.0},
  { id: 16, title: "Sangeet XYZ", image: "/images/sangeet.png", url: "https://sangeet.xyz/", rating: 2.17},
  { id: 17, title: "Wallen Art", image: "/images/wallenart.png", url: "https://wallenart.dev/", rating: 4.42},
  { id: 18, title: "Haseeb One", image: "/images/haseeb.png", url: "https://www.haseeb.one/", rating: 2.0},
  { id: 19, title: "Musaaqeel", image: "/images/musaaqeel.png", url: "https://musaaqeel.com/", rating: 2.67},
  { id: 20, title: "Magma Bits", image: "/images/magmabits.png", url: "https://magmabits.vercel.app/", rating: 2.33},
  { id: 21, title: "F20180445 Portfolio", image: "/images/f20180445.png", url: "https://f20180445.github.io/portfolio-app/", rating: 1.33},
  { id: 22, title: "Hecker VC", image: "/images/hecker.png", url: "https://hecker.vc/", rating: 1.83},
  { id: 29, title: "Trobo Dev", image: "/images/trobo.png", url: "https://www.trobo.dev/", rating: 3.0},
  { id: 30, title: "Lefkos Dev", image: "/images/lefkos.png", url: "https://lefkos.dev/", rating: 3.33},
  { id: 31, title: "SBhanushali", image: "/images/sbhanushali.png", url: "https://sbhanushali2010.github.io/", rating: 1.83},
  { id: 32, title: "Im Radhe", image: "/images/imradhe.png", url: "https://imradhe.com/", rating: 2.0},
  { id: 33, title: "Purna Codes", image: "/images/purnacodes.png", url: "https://purnacodes.github.io/my_portfolio_site/", rating: 2.33},
  { id: 34, title: "Abdul Haq", image: "/images/abdulhaq.png", url: "https://abdulhaq.me/", rating: 2.17},
  { id: 35, title: "5Cover Portfolio", image: "/images/5cover.png", url: "https://5cover.github.io/portfolio/fr/index.html", rating: 2.5},
  { id: 36, title: "Milena Saron", image: "/images/milenasaron.png", url: "https://milenasaron.vercel.app/", rating: 2.83},
  { id: 37, title: "Esdras Caleb", image: "/images/esdrascaleb.png", url: "https://esdrascaleb.github.io/", rating: 2.33},
  { id: 38, title: "Tshepo Portfolio", image: "/images/tshepo.png", url: "https://tshepo-online-portfolio.netlify.app/", rating: 2.83},
  { id: 39, title: "Pranabesh", image: "/images/pranabesh.png", url: "https://www.pranabesh.com", rating: 3.0},
  { id: 40, title: "Gupta Somnath", image: "/images/guptasomnath.png", url: "https://guptasomnath.github.io/portfolio/", rating: 2.83},
  { id: 41, title: "Sumaira Ahmed", image: "/images/sumairaahmed.png", url: "https://sumairaahmedcode.github.io/Sumaira-Ahmed-Portfolio.github.io/", rating: 2.33},
  { id: 42, title: "Natsha", image: "/images/natsha.png", url: "https://natsha.me/", rating: 4.5, recommended: true},
  { id: 43, title: "Muscaa", image: "/images/muscaa.png", url: "https://muscaa.github.io/portfolio/", rating: 3.5},
  { id: 44, title: "Eric Augusto", image: "/images/ericaugusto.png", url: "https://ericaugusto.pages.dev/en", rating: 3.83},
  { id: 45, title: "Gauransh Mathur", image: "/images/gauranshmathur.png", url: "http://gauranshmathur.site", rating: 2.0},
  { id: 46, title: "Udit Rajput", image: "/images/uditrajput.png", url: "https://uditrajput.vercel.app/", rating: 3.67},
  { id: 47, title: "Sahil Verma", image: "/images/sahilverma.png", url: "https://sahilverma.dev/", rating: 4.17},
  { id: 48, title: "Christos Kakoulakis", image: "/images/christoskakoulakis.png", url: "https://christos-kakoulakis.gr/", rating: 0.83},
  { id: 49, title: "Ana117", image: "/images/ana117.png", url: "https://ana117.github.io/", rating: 3.67},
  { id: 50, title: "Luckey Duckey", image: "/images/luckeyduckey.png", url: "https://luckeyduckey.github.io", rating: 3.08},
  { id: 51, title: "J Zitnik", image: "/images/jzitnik.png", url: "https://jzitnik.dev/en", rating: 4.08},
  { id: 52, title: "Shinobi8894", image: "/images/shinobi8894.png", url: "https://shinobi8894.onrender.com/", rating: 1.83},
  { id: 53, title: "Sector32", image: "/images/sector32.png", url: "https://www.sector32.net/", rating: 3.83},
  { id: 54, title: "Reynata Arya", image: "/images/reynataarya.png", url: "https://reynataarya.github.io/portfolioprofile/", rating: 2.17},
  { id: 55, title: "Jonathan Bout", image: "/images/jonathanbout.png", url: "https://jonathanbout.com", rating: 2.67},
  { id: 56, title: "Flaming Hot Cheetos", image: "/images/flaminghotcheetos.png", url: "https://flaminghotcheetos69.github.io/portfolio/", rating: 3.33},
  { id: 57, title: "Clever Developer", image: "/images/cleverdeveloper.png", url: "https://www.cleverdeveloper.in/", rating: 4.08},
  { id: 58, title: "Divyansh K", image: "/images/divyanshk.png", url: "https://divyanshk.xyz/", rating: 3.58},
  { id: 59, title: "Brandon Buhr", image: "/images/brandonbuhr.png", url: "https://brandonbuhrdev.com", rating: 4.0},
  { id: 60, title: "Bilal Ahmed", image: "/images/bilalahmed.png", url: "https://bilalahmedbaf-03.netlify.app", rating: 3.25},
  { id: 61, title: "Ahmad Imam", image: "/images/ahmadimam.png", url: "https://ahmad-imam.vercel.app", rating: 4.0},
  { id: 62, title: "KK Mihai", image: "/images/kkmihai.png", url: "https://kkmihai.is-cool.dev/", rating: 4.0},
  { id: 63, title: "Cadence Higgins", image: "/images/cadencehiggins.png", url: "https://www.cadencehiggins.com/", rating: 3.5},
  { id: 64, title: "Jezyk182", image: "/images/jezyk182.png", url: "https://jezyk182.github.io/portfolio/", rating: 3.5},
  { id: 65, title: "Ni30", image: "/images/ni30.png", url: "https://ni30.vercel.app/", rating: 3.08},
  { id: 66, title: "Jose Cruz", image: "/images/josecruz.png", url: "https://josecruz96.netlify.app/", rating: 3.5},
  { id: 67, title: "Amar Tripathi", image: "/images/amartripathi.png", url: "https://amartripathi.vercel.app", rating: 3.5},
  { id: 68, title: "Sugith", image: "/images/sugith.png", url: "https://sugith.in", rating: 4.75},
  { id: 69, title: "Rishi Lahoti", image: "/images/rishilahoti.png", url: "https://rishilahoti.works", rating: 3.75},
  { id: 70, title: "Know Keshav", image: "/images/knowkeshav.png", url: "https://knowkeshav.netlify.app/", rating: 3.5},
  { id: 71, title: "Montel26", image: "/images/montel26.png", url: "https://montel26.web.app/", rating: 1.92},
  { id: 72, title: "Krousky Stepan", image: "/images/krouskystepan.png", url: "https://krouskystepan.com", rating: 3.08},
  { id: 73, title: "Santiago Garcia", image: "/images/santiagogarcia.png", url: "https://www.santiagogarcia.site/", rating: 3.83},
  { id: 74, title: "Law Light", image: "/images/lawlight.png", url: "https://lawlight.org", rating: 3.17},
  { id: 75, title: "Joonas Vaija", image: "/images/joonasvaija.png", url: "https://www.joonasvaija.fi/", rating: 3.33},
  { id: 76, title: "Ted Awf", image: "/images/tedawf.png", url: "https://tedawf.com", rating: 4.67},
  { id: 77, title: "Nsoro Allan", image: "/images/nsoroallan.png", url: "https://nsoroallan.netlify.app", rating: 2.33},
  { id: 78, title: "Tejas Bhovad", image: "/images/tejasbhovad.png", url: "https://tejasbhovad.com/", rating: 2.83},
  { id: 79, title: "Amr Mugl", image: "/images/amrmugl.png", url: "https://amrmugl.dev", rating: 3.75},
  { id: 80, title: "Piyush Portfolio", image: "/images/piyush.png", url: "https://piyush-portfolio-lyart.vercel.app/", rating: 2.42},
  { id: 81, title: "Jaskirat Oberoi", image: "/images/jaskiratoberoi.png", url: "https://jaskiratoberoi.com", rating: 2.58},
  { id: 82, title: "Craftz Dog", image: "/images/craftzdog.png", url: "https://www.craftz.dog/", rating: 3.0},
  { id: 83, title: "0xDev", image: "/images/0xdev.png", url: "https://0xdev.in", rating: 2.58},
  { id: 84, title: "Baf-03", image: "/images/baf03.png", url: "https://github.com/Baf-03", rating: 2.75},
  { id: 85, title: "Dev Xoshakya", image: "/images/devxoshakya.png", url: "https://devxoshakya.xyz", rating: 3.17},
  { id: 86, title: "Bryan Lee", image: "/images/bryanlee.png", url: "https://www.bryanleezh.dev/", rating: 4.5},
  { id: 87, title: "Ahmed Raza", image: "/images/ahmedraza.png", url: "https://ahmed-raza-portfolio.vercel.app/", rating: 3.42},
  { id: 88, title: "Tobi Studio", image: "/images/tobistudio.png", url: "https://tobi-studio.vercel.app/", rating: 3.67},
  { id: 89, title: "Greiner Petter", image: "/images/greinerpetter.png", url: "https://www.greiner-petter.net/", rating: 3.42},
  { id: 90, title: "Tino D", image: "/images/tinod.png", url: "https://www.tinod.me", rating: 4.17},
  { id: 91, title: "Nikunj Borad", image: "/images/nikunjborad.png", url: "https://nikunjborad.tech/", rating: 3.25},
  { id: 92, title: "Daniyal Ali", image: "/images/daniyalali.png", url: "https://daniyalali.netlify.app/", rating: 2.17},
  { id: 93, title: "Shoji Yamamoto", image: "/images/shojiyamamoto.png", url: "https://shoji-yamamoto-portfolio.vercel.app/", rating: 4.5},
  { id: 94, title: "Elargoubi", image: "/images/elargoubi.png", url: "https://elargoubi.com", rating: 3.58},
  { id: 95, title: "Hollowww", image: "/images/hollowww.png", url: "https://hollowww.dev", rating: 4.17},
  { id: 96, title: "Ayoub Jouda", image: "/images/ayoubjouda.png", url: "https://ayoubjouda.me", rating: 3.83},
  { id: 97, title: "Jarno Willems", image: "/images/jarnowillems.png", url: "https://jarnowillems.vercel.app/", rating: 2.75},
  { id: 98, title: "Bitbuster Portfolio", image: "/images/bitbuster.png", url: "https://bitbuster-portfolio.vercel.app/", rating: 4.08},
  { id: 99, title: "Khalifa Studio", image: "/images/khalifastudio.png", url: "https://khalifa.studio/", rating: 3.5},
  { id: 100, title: "R1 Design", image: "/images/r1design.png", url: "https://r1design.co/", rating: 2.58},
  { id: 101, title: "Bilal Ahmed", image: "/images/bilalahmed.png", url: "https://bilalahmedbaf-03.netlify.app/", rating: 2.67},
  { id: 102, title: "Manas Upadhyay", image: "/images/manasupadhyay.png", url: "https://manasupadhyay.vercel.app", rating: 2.83},
  { id: 103, title: "Abhishek Shankar", image: "/images/abhishekshankar.png", url: "https://abhishekshankar.net", rating: 3.0},
  { id: 104, title: "Seevt Dev", image: "/images/seevtdev.png", url: "https://seevt.dev/", rating: 4.0},
  { id: 105, title: "George Ckito", image: "/images/georgeckito.png", url: "https://www.georgeckito.xyz", rating: 3.83},
  { id: 106, title: "Krishna Kumar", image: "/images/krishnakumar.png", url: "https://www.krishnakumar.dev", rating: 3.5},
  { id: 107, title: "SKF Yi", image: "/images/skfyi.png", url: "https://skfyi.com", rating: 2.83},
  { id: 108, title: "Ricardo Morais", image: "/images/ricardomorais.png", url: "https://www.ricardomorais.dev/", rating: 3.58},
  { id: 109, title: "Feti Portfolio", image: "/images/fetiportfolio.png", url: "https://feti-portfolio.vercel.app/", rating: 3.67},
  { id: 110, title: "Dilgash", image: "/images/dilgash.png", url: "https://dilgash.com", rating: 2.83},
  { id: 111, title: "Nik Don", image: "/images/nikdon.png", url: "https://nikdon.com", rating: 2.5},
  { id: 112, title: "Yute October", image: "/images/yuteoctober.png", url: "https://yuteoctober.github.io/wins95Portfolio/", rating: 4.5},
  { id: 113, title: "Alpha OG", image: "/images/alphaog.png", url: "https://alpha-og.github.io/portfolio/", rating: 2.33},
  { id: 114, title: "Mahesh Paul", image: "/images/maheshpaul.png", url: "https://maheshpaul.vercel.app", rating: 2.5},
  { id: 115, title: "Liel Amar", image: "/images/lielamar.png", url: "https://lielamar.com", rating: 3.08},
  { id: 116, title: "Specy App", image: "/images/specyapp.png", url: "https://portfolio.specy.app", rating: 3.5},
  { id: 117, title: "Oskar Franttiglen", image: "/images/oskarfranttiglen.png", url: "https://oskarfranttiglen.com", rating: 4.0},
  { id: 118, title: "Chrisma Portfolio", image: "/images/chrisma.png", url: "https://portfolio-chrisma.vercel.app/", rating: 3.17},
  { id: 119, title: "ADS Labs", image: "/images/adslabs.png", url: "https://adslabs.devxoshakya.xyz", rating: 2.5},
  { id: 120, title: "K Dev", image: "/images/kdev.png", url: "https://www.kdev.app", rating: 3.83},
  { id: 121, title: "Talut Tech", image: "/images/taluttech.png", url: "https://portfolio.talut.tech", rating: 3.42},
  { id: 122, title: "Praveen Shinde", image: "/images/praveenshinde.png", url: "https://praveenshinde.com/", rating: 3.17},
  { id: 123, title: "Faizan Asad", image: "/images/faizanasad.png", url: "https://faizanasad.com", rating: 2.83},
  { id: 124, title: "Tomiwa Portfolio", image: "/images/tomiwa.png", url: "https://tomiwas-portfolio-two.vercel.app/", rating: 2.58},
  { id: 125, title: "Dipak Giri", image: "/images/dipakgiri.png", url: "https://portfolio.dipakgiri12.com.np/", rating: 2.42},
  { id: 126, title: "Sophia Anina", image: "/images/sophiaanina.png", url: "http://sophiaanina.com/portfolio/indeks.html", rating: 2.33},
  { id: 127, title: "Salman AI", image: "/images/salmanai.png", url: "https://salmanai.com", rating: 3.17},
  { id: 128, title: "Stefan Topalovic", image: "/images/stefantopalovic.png", url: "https://www.stefantopalovic.com/", rating: 2.75},
  { id: 129, title: "Kan Nguyen", image: "/images/kannguyen.png", url: "https://kannguyen.netlify.app/", rating: 3.0},
  { id: 130, title: "Ben Codes", image: "/images/bencodes.png", url: "https://bencodes.de", rating: 4.17},
  { id: 131, title: "I Waqar", image: "/images/iwaqar.png", url: "https://www.iwaqar.com/", rating: 1.83},
  { id: 132, title: "Ayush Anand", image: "/images/ayushanand.png", url: "https://ayushanandhd.github.io/", rating: 2.33},
  { id: 133, title: "Galdi Dev", image: "/images/galdi.png", url: "https://www.galdi.dev/", rating: 2.75},
  { id: 134, title: "Sankalp Jaiswal", image: "/images/sankalpjaiswal.png", url: "https://sankalp-jaiswal-portfolio.vercel.app/", rating: 3.83},
  { id: 135, title: "Supermoooo", image: "/images/supermoooo.png", url: "https://supermoooo.github.io/MyPortfolio/", rating: 4.33},
  { id: 136, title: "Andrija Web", image: "/images/andrijaweb.png", url: "https://andrijaweb.vercel.app", rating: 4.58},
  { id: 137, title: "Joe Riveugelen", image: "/images/joeriveugelen.png", url: "https://joeriveugelen.com//", rating: 4.0},
  { id: 138, title: "Vishaal Venkatesan", image: "/images/vishaalvenkatesan.png", url: "https://www.vishaalvenkatesan.engineer", rating: 3.67},
  { id: 139, title: "Levente Otta", image: "/images/leventeotta.png", url: "https://leventeotta.com/", rating: 3.5},
  { id: 140, title: "Eleven Kamesh", image: "/images/elevenkamesh.png", url: "https://elevenkamesh.github.io/terminal_portfolio-/", rating: 2.17},
  { id: 141, title: "Darrel Traballo", image: "/images/darreltraballo.png", url: "https://darreltraballo.github.io", rating: 2.92},
  { id: 142, title: "Sujal", image: "/images/sujal.png", url: "https://sujal.xyz", rating: 2.33},
  { id: 143, title: "Cory Parrish", image: "/images/coryparrish.png", url: "https://www.coryparrish.dev/", rating: 2.0},
  { id: 144, title: "Max Tull", image: "/images/maxtull.png", url: "https://maxtull.xyz", rating: 3.33},
  { id: 145, title: "Corie Watson", image: "/images/coriewatson.png", url: "https://coriewatson.me", rating: 3.42},
  { id: 146, title: "Yuta Abe", image: "/images/yutaabe.png", url: "https://yuta-abe.com/", rating: 3.83},
  { id: 147, title: "Prasoon V2", image: "/images/prasoonv2.png", url: "https://prasoon-v2.vercel.app/", rating: 5.0},
  { id: 148, title: "Altaiar", image: "/images/altaiar.png", url: "https://altaiar.dev", rating: 3.5},
  { id: 149, title: "Damian Briones", image: "/images/damianbriones.png", url: "https://damian-briones-portfolio.vercel.app", rating: 4.08},
  { id: 150, title: "Boris Ten Kes", image: "/images/boristenkes.png", url: "https://boristenkes.com", rating: 3.17},
  { id: 151, title: "Rafael Amaral", image: "/images/rafaelamaral.png", url: "https://rafaelamaral.dev/", rating: 4.58},
  { id: 152, title: "Carson Develops", image: "/images/carsondevelops.png", url: "https://carsondevelops.xyz", rating: 3.42},
  { id: 153, title: "Inky Beta", image: "/images/inkybeta.png", url: "https://portfolio-inky-beta-47.vercel.app/", rating: 2.92},
  { id: 154, title: "Gaurish", image: "/images/gaurish.png", url: "https://gaurish.xyz", rating: 3.67},
  { id: 155, title: "Keval Shah", image: "/images/kevalshah.png", url: "https://keval-shah.netlify.app/", rating: 4.0},
  { id: 156, title: "David Kozdra", image: "/images/davidkozdra.png", url: "https://davidkozdra.com", rating: 3.33},
  { id: 157, title: "Stecca Dev", image: "/images/steccadev.png", url: "https://me.stecca.dev", rating: 2.92},
  { id: 158, title: "Paras Shenmare", image: "/images/parasshenmare.png", url: "https://parasshenmare.vercel.app", rating: 4.08},
  { id: 159, title: "Reece Harris", image: "/images/reeceharris.png", url: "https://reeceharris.net", rating: 3.33},
  { id: 160, title: "Virid Mu", image: "/images/viridmu.png", url: "http://portfolio-virid-mu-48.vercel.app/", rating: 3.58},
  { id: 161, title: "Kuray", image: "/images/kuray.png", url: "https://kuray.dev", rating: 3.17},
  { id: 162, title: "Carlos Dubon", image: "/images/carlosdubon.png", url: "https://carlosdubon.dev", rating: 3.75},
  { id: 163, title: "Aymane Chakar", image: "/images/aymanechakar.png", url: "https://aymanechakar.vercel.app/", rating: 4.25},
  { id: 164, title: "Codewarnab", image: "/images/codewarnab.png", url: "https://codewarnab.in/", rating: 2.42},
  { id: 165, title: "Lorenzo Palaia", image: "/images/lorenzopalaia.png", url: "https://lorenzopalaia.it", rating: 3.33 },
]